### ISSUE TITLE
Using PatrolJS with multiple navmeshes

### ISSUE THREAD

**Issue by ghost** [nickjanssen/PatrolJS#3]
Is there any way to use PatrolJS with multiple meshes? For example if current position and destination are on different navmeshes. How to find path between two navmeshes? Thanks.

**Comment by nickjanssen** [comment]
@Gugis this is not possible. If you want to find a path between two navmeshes, you would need to merge them into one mesh. Can you explain your usecase?

**Comment by ghost** [comment]
@nickjanssen I have large terrain and it's sliced to multiple chunks. I guess every slice off terain should have it's own navmesh. Right? Then I need solution how to navigate from one mesh to another.

**Comment by nickjanssen** [comment]
@Gugis correct! As I said before, you would need to merge them into one mesh, otherwise you can't have a connection between the two meshes.
