### ISSUE TITLE
can this handle multiple agents?

### ISSUE THREAD

**Issue by frnsys** [nickjanssen/PatrolJS#4]
does this library support having multiple agents that need to avoid colliding with one another?

**Comment by nickjanssen** [comment]
@frnsys definitely! This was actively used in a MMORPG with many objects requiring pathfinding.

**Comment by frnsys** [comment]
oh amazing! Do you have a snippet example? I will double check to see if there's one available too.

**Comment by nickjanssen** [comment]
I'm not sure I understand your question. A snippet to avoid colliding with each other?
To be clear, this library does not come with such features but it does not prevent you from implementing such code that would run in parallel with PatrolJS.

**Comment by frnsys** [comment]
oh by "support" I was asking if that kind of functionality was included with the library - but thank you anyways, it's fantastic and very helpful nonetheless :)

**Comment by nickjanssen** [comment]
Great to hear! Thanks :)
