### ISSUE TITLE
Checking 'typeof module' not an ideal way to detect Node.js

### ISSUE THREAD

**Issue by donmccurdy** [nickjanssen/PatrolJS#6]
Hi! Neat package you've written here. :)

I'd like to use PatrolJS on the browser, without necessarily copy/pasting the script into my build. Using Browserify would normally make this easy, but it appears that PatrolJS is relying on `typeof module` as an indicator of whether the code is running server-side or not:

```
  if (typeof module !== 'undefined' && module.exports) {
    _ = require('underscore');
    THREE = require('three');
    ProgressBar = require('progress');
  }
  else {
    _ = window._;
    THREE = window.THREE;

    // stub in the browser
    ProgressBar = function () {
      return {
        tick: function () {}
      };
    };
  }
```

This isn't really ideal, as the same CommonJS module system can be used for browser-side code. Perhaps detecting `process` would be better?

**Comment by nickjanssen** [comment]
FYI I've added a link to your repo in the readme. Nice work! :)
