### ISSUE TITLE
(FYI) Working on some updates in a fork

### ISSUE THREAD

**Issue by donmccurdy** [nickjanssen/PatrolJS#7]
Hi @nickjanssen — Wanted to give you a heads up that I'm making some updates to PatrolJS for use with [A-Frame](https://aframe.io/) and more recent JS tooling.

Planned changes:

- Remove dependency on Underscore (in favor of ES5)
- Remove dependency on ProgressBar
- Support CommonJS in the browser (see #6)
- Allow logs to be disabled
- Expose a little more API surface for the nav mesh, e.g. so that users of the library can inspect the current node (and perhaps get the color of the face, to interpret for gameplay?)

It's not clear whether PatrolJS is still maintained (i understand time/energy are limited of course), so I've chosen to begin in a [new repository](https://github.com/donmccurdy/three-pathfinding). It's not my intention to create a competing library unnecessarily, so please let me know if these are changes you would welcome as PRs here, instead.

Thanks, and nice work!

**Comment by nickjanssen** [comment]
Hi @donmccurdy,

My apologies for my late reply (I only now saw there's issues and PRs, I got an email through the mention), and thank you for your work. I'm indeed extremely busy with other things right now, but I do applaud your efforts and appreciate your mention of a fork. I'll check it out from time to time!

**Comment by donmccurdy** [comment]
Sounds good, all the best!
