### ISSUE TITLE
Is there a support for composite navmeshes?

### ISSUE THREAD

**Issue by DenisTis** [nickjanssen/PatrolJS#9]
For example if navmesh contains water and ground and character can only go through water with specific item. 
Example: navmesh areas in Unity here 
https://docs.unity3d.com/560/Documentation/Manual/nav-AreasAndCosts.html

Can I achieve the same in Patroljs?

**Comment by nickjanssen** [comment]
Not out of the box. However, there might be a way to tag polygons inside of Blender with a type (ground, water, etc) and modify PatrolJS so it can read these tagged polygons, and then adjust `findPath` so each vector contains the type of the path traversed.
